version: '3.7'
services:
  postgres:
    env_file:
      - development.env

  app:
    env_file:
      - development.env
    build:
        context: ./
        dockerfile: Dockerfile
        target: builder
    volumes:
      - type: bind
        source: ./client
        target: /app/client
      - type: bind
        source: ./server
        target: /app/server
      # - type: bind
      #   source: ./script
      #   target: /app/script
      # - type: volume
      #   source: node_modules_dev
      #   target: /app/node_modules
    command: ["npm", "run", "start-dev"]

# volumes:
#   node_modules_dev: